### ISSUE TITLE
Icon is stretched in overflow menu

### ISSUE THREAD

**Issue by Keith94** [andymckay/sort-tabs-by-url#10]
In the new photon overflow menu, the add-on icon looks wrong:

![image](https://user-images.githubusercontent.com/5490615/27225976-81c6dd2a-5251-11e7-8363-c16afa72eddb.png)

**Comment by andymckay** [comment]
Not related to this add-on, happens to all add-ons at the moment: https://bugzilla.mozilla.org/show_bug.cgi?id=1368854
