### ISSUE TITLE
Add support for Tab Groups

### ISSUE THREAD

**Issue by Keith94** [andymckay/sort-tabs-by-url#6]
https://addons.mozilla.org/addon/tab-groups-panorama/

Currently, using "Sort Tabs" in a certain tab group will also affect tabs within other tab groups. So, it might be good to only sort tabs within current tab group.

**Comment by andymckay** [comment]
Do tab groups expose any sort of APIs to WebExtensions to make this possible?

**Comment by Quicksaver** [comment]
> Do tab groups expose any sort of APIs to WebExtensions to make this possible?

No. Not yet at least.

**Comment by Quicksaver** [comment]
FYI Tab Groups uses the [browser's own tab visibility features](https://dxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#2979-3034). Exposing the tab's visibility state in the tabs API should work; visible tabs = in current group.

**Comment by andymckay** [comment]
Looks like we don't have that in the tabs API

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/query
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab

Would probably need adding.

**Comment by Keith94** [comment]
The add-on now works as expected wherein it ignores tabs that are hidden and sorts only the visible ones. :)
